modules/produccion/__init__.py
from flask import Blueprint


produccion = Blueprint('produccion', __name__, template_folder="../templates")
from . import routes

modules/produccion/routes.py
from flask import render_template
from flask import render_template, request, jsonify, url_for, redirect, flash
from models import db, Receta, Produccion, RecetaDetalle, MateriaPrima, MermaMateriaPrima, CostoGalleta, Tipo_Materia
from . import produccion
from controllers.controller_login import requiere_rol, requiere_token
from flask_login import login_required, current_user
from datetime import datetime, date
from sqlalchemy import asc
from controllers.controller_materia_prima import actualizar_cantidades_tipo
from controllers.controller_login import requiere_token

@produccion.route("/produccion", methods=["GET"])
@login_required
@requiere_token
@requiere_rol("admin", "produccion")
def vista_produccion():
    recetas = Receta.query.filter_by(estatus=1).all()
    solicitudes = Produccion.query.filter_by(estatus='solicitud').all()
    solicitudes_en_proceso = Produccion.query.filter_by(estatus='proceso').all()
    solicitudes_canceladas = Produccion.query.filter_by(estatus='cancelada').all()
    solicitudes_postergadas = Produccion.query.filter_by(estatus='postergada').all()
    
    return render_template("moduloProduccion/produccion.html", recetas=recetas, solicitudes=solicitudes, solicitudes_en_proceso=solicitudes_en_proceso, 
                           solicitudes_canceladas=solicitudes_canceladas, solicitudes_postergadas=solicitudes_postergadas)

@produccion.route('/solicitarProduccion', methods=['POST'])
@login_required
@requiere_token
@requiere_rol('admin', "produccion")
def solicitar_produccion():
    # Se recupera el id de la solicitud y la receta
    id_solicitud = request.form['solicitud_id']
    receta_id = request.form['receta_id']
    
    # Actualizar el estatus de la solicitud a 'proceso'
    solicitud = Produccion.query.get(id_solicitud)
    solicitud.estatus = 'proceso'
    solicitud.empleadoProduccion = current_user.nombre

    # Recuperar los detalles de la receta
    detalles_receta = RecetaDetalle.query.filter_by(receta_id=receta_id).all()
    
    receta = Receta.query.get(receta_id)

    # Actualizar las cantidades de materia prima
    for detalle in detalles_receta:
        # Bandera para verificar si se encontraron suficientes insumos para este detalle
        insumos_suficientes = False
        
        cantidad_necesaria = detalle.cantidad_necesaria
        unidad_origen = detalle.unidad_medida

        # Recuperar las materias primas disponibles ordenadas por fecha de caducidad ascendente
        materias_primas_disponibles = MateriaPrima.query.filter_by(id_tipo_materia=detalle.tipo_materia_id)\
                                                        .order_by(asc(MateriaPrima.fecha_caducidad)).all()

        # Convertir la cantidad necesaria a la unidad de medida de la primera materia prima disponible
        cantidad_restante = convertir_unidades(cantidad_necesaria, unidad_origen, materias_primas_disponibles[0].tipo)
        ids_materias = []
        # Si hay un porcentaje de merma, calcularlo


        # Recorrer las materias primas disponibles hasta encontrar suficiente cantidad
        for materia_prima in materias_primas_disponibles:
            cantidad_disponible = convertir_unidades(materia_prima.cantidad_disponible,
                                                     materia_prima.tipo, materia_prima.tipo)
            ids_materias.append(materia_prima.id)
            # Si la cantidad disponible es suficiente, actualizar y salir del bucle
            if cantidad_disponible >= cantidad_restante:
                materia_prima.cantidad_disponible -= cantidad_restante
                insumos_suficientes = True  # Actualizar la bandera

                break
            else:
                # Si no es suficiente, consumir toda la cantidad disponible y actualizar cantidad restante
                cantidad_restante -= cantidad_disponible
                materia_prima.cantidad_disponible = 0


        # Si no hay suficientes insumos para algún detalle de receta, mostrar mensaje de error y redireccionar
        if not insumos_suficientes:
            flash(f'No hay suficiente cantidad de materia prima para el detalle de receta {detalle.id}.', 'error')
            return redirect(url_for("produccion_blueprint.vista_produccion"))


        # Si hay suficientes insumos, procesar el porcentaje de merma
        merma_porcentaje = 0
        if detalle.merma_porcentaje and detalle.merma_porcentaje != 0:
            porcentaje = detalle.merma_porcentaje / 100
            merma_porcentaje = detalle.cantidad_necesaria * porcentaje
            merma_porcentaje = merma_porcentaje/len(ids_materias)

        if merma_porcentaje != 0:
            for mmateria_id in ids_materias:
                    nueva_merma = MermaMateriaPrima(
                        materia_prima_id=mmateria_id,
                        cantidad=merma_porcentaje,
                        descripcion=f'Merma producida por {detalle.merma_porcentaje}% por producción de la receta de {receta.nombre}',
                        tipo=detalle.unidad_medida,  # investigar qué dato va en esta variable
                        fecha=datetime.now(),
                        estatus=1
                    )
                    db.session.add(nueva_merma)
            
        # Actualizar la cantidad disponible de la materia prima
        tipo_materia = Tipo_Materia.query.get(detalle.tipo_materia_id)
        cantidad_a_restar = convertir_unidades(detalle.cantidad_necesaria, detalle.unidad_medida, tipo_materia.tipo)
        tipo_materia.cantidad_disponible -= cantidad_a_restar

    # Si se completó la iteración sin problemas, entonces todos los detalles de receta tienen suficientes insumos
    # Procesar la solicitud completa
    try:
        db.session.commit()
        actualizar_cantidades_tipo()
        flash('La solicitud de producción se ha procesado correctamente.', 'success')
    except Exception as e:
        db.session.rollback()
        actualizar_cantidades_tipo()
        flash('Error al procesar la solicitud de producción. Inténtelo de nuevo más tarde.', 'error')
        #current_app.logger.error(f'Error al procesar la solicitud de producción: {str(e)}')

    return redirect(url_for("produccion_blueprint.vista_produccion"))



    


def convertir_unidades(cantidad, unidad_origen, unidad_destino):
    print(f"Convirtiendo {cantidad} {unidad_origen} a {unidad_destino}")
    conversiones = {
        ('g', 'kg'): lambda x: x / 1000,
        ('kg', 'g'): lambda x: x * 1000,
        ('ml', 'l'): lambda x: x / 1000,
        ('l', 'ml'): lambda x: x * 1000,
        ('kg', 'pz'): lambda x: (x / 1000)  / 50,
        ('g', 'pz'): lambda x: x /50,
        ('pz', 'g'): lambda x: x * 50,
        ('pz', 'kg'): lambda x: x * 0.050,
        
        
    }
    
    if unidad_origen == unidad_destino:
        return cantidad

    if (unidad_origen, unidad_destino) in conversiones:
        resultado = conversiones[(unidad_origen, unidad_destino)](cantidad)
        print(f"Resultado: {resultado}")
        return resultado
    else:
        print("Las unidades de medida no son compatibles")




@produccion.route("/postergarProduccion", methods=["POST"])
@login_required
@requiere_token
@requiere_rol("admin", "produccion")
def postergar_produccion():
    id_solicitud = request.form['solicitud_id']

    solicitud = Produccion.query.get(id_solicitud)
    
    solicitud.fecha_cancelado = datetime.now()
    solicitud.estatus = 'postergada'
    
    db.session.commit()  # Aquí se realiza el commit en el objeto de sesión db.session
    flash('La solicitud de producción se ha postergado correctamente.', 'info')
    
    return redirect(url_for("produccion_blueprint.vista_produccion"))


@produccion.route("/terminarProduccion", methods=["POST"])
@login_required
@requiere_token
@requiere_rol("admin", "produccion")
def terminar_produccion():
    id_solicitud = request.form['solicitud_id']
    receta_id = request.form['receta_id']
    
    # Actualizar el estatus de la solicitud a 'proceso'
    solicitud = Produccion.query.get(id_solicitud)
    solicitud.estatus = 'terminada'
    solicitud.fecha_producido = datetime.now()
    solicitud.lote = "prod-"+date.today().strftime('%d/%m/%Y')+'-'+solicitud.receta.nombre


    # Recuperar los detalles de la receta
    detalles_receta = RecetaDetalle.query.filter_by(receta_id=receta_id).all()
    
    receta = Receta.query.get(receta_id)
    
    costo_galleta = CostoGalleta.query.filter_by(id = receta.id_precio).first()
    # for detalle in detalles_receta:
    #     if not detalle.merma_porcentaje or detalle.merma_porcentaje == 0:
    #             print("no hay porcentaje de merma")
    #     else:
    #         porcentaje = detalle.merma_porcentaje / 100
            
    #         merma_porcentaje = (detalle.cantidad_necesaria * porcentaje)
            
    #         nueva_merma = MermaMateriaPrima(
    #             materia_prima_id=detalle.tipo_materia_id,
    #             cantidad = merma_porcentaje,
    #             descripcion = f'Merma producida por {detalle.merma_porcentaje}% de la receta con id {receta_id}',
    #             tipo = detalle.unidad_medida, # investigar qué dato va en esta variable
    #             fecha = datetime.now(),
    #             estatus = 1
    #         )
    #         db.session.add(nueva_merma)
        
    #     tipo_materia = Tipo_Materia.query.get(detalle.tipo_materia_id)
    #     cantidad_a_restar = convertir_unidades(detalle.cantidad_necesaria, detalle.unidad_medida, tipo_materia.tipo)
    #     tipo_materia.cantidad_disponible -= cantidad_a_restar
        
        
    # Actualizar stock de las galletas
    costo_galleta.galletas_disponibles += receta.num_galletas
    solicitud.galletas_disponibles = receta.num_galletas

    # Realizar el commit de todas las actualizaciones de la materia prima
    try:
        db.session.commit()
        flash('La solicitud de producción se ha terminado correctamente.', 'success')
    except Exception as e:
        db.session.rollback()

modules/solicitudProduccion/__init__.py
from flask import Blueprint


solicitud_produccion = Blueprint('solicitudProduccion', __name__, template_folder="../templates")
from . import routes

modules/solicitudProduccion/routes.py
from . import solicitud_produccion
from flask import render_template, request, jsonify, url_for, redirect, flash
#from formularios import formSolicitudProduccion
from controllers.controller_login import requiere_rol
from flask_login import login_required, current_user
from models import db, Receta, Produccion
import json
from datetime import datetime
from controllers.controller_login import requiere_token


@solicitud_produccion.route("/solicitudProduccion", methods=["GET"])
@login_required
@requiere_token
@requiere_rol("admin", "inventario", "venta", "produccion")
def vista_recetas():
    recetas = Receta.query.filter_by(estatus=1).all()
    solcitudes = Produccion.query.all()

    return render_template("moduloProduccion/solicitudProduccion.html", recetas=recetas, solicitudes=solcitudes)

@solicitud_produccion.route("/agregarSolicitud", methods=["POST"])
@login_required
@requiere_token
@requiere_rol("admin", "inventario", "venta", "produccion")
def agregar_solicitud():
    # id_receta = request.form.get("receta_id")
    id_receta = request.form['receta_id']

    receta = Receta.query.get(id_receta)
    if not receta or receta.id_precio is None:
        flash('La receta no tiene precio, debe asignar un precio antes de procesar la solicitud.', 'error')
        return redirect(url_for("solicitudProduccion.vista_recetas"))

    nueva_solicitud = Produccion(
        receta_id=id_receta,
        estatus='solicitud',
        cantidad=1, # Este dato falta por confirmar qué es
        fecha_solicitud=datetime.now(),
        fecha_producido=None,
        fecha_postergado=None,
        empleadoSolicitante = current_user.nombre
    )
    
    db.session.add(nueva_solicitud)
    db.session.commit()
    flash("Solicitud de producción agregada", "info")

    return redirect(url_for("solicitudProduccion.vista_recetas"))

templates/moduloProduccion/solicitudProduccion.html
{% extends 'layout.html' %}

{% block content %}
{% from "_macros.html" import render_field %}

<style>
    section {
        display: flex;
        flex-wrap: wrap; 
        justify-content: center; 
        gap: 20px; 
        max-width: 1000px; 
        margin: auto; 
    }

    section figure {
        width: 250px;
        height: 250px;
        text-align: center; 
        position: relative; 
    }

    section img {
        width: 100%;
        height: 100%;
        border-radius: 50%;
        object-fit: cover;
        opacity: .8;
        transition: .5s ease;
    }

    section img:hover {
        cursor: pointer;
        transform: scale(1.1);
        opacity: 1;
        filter: contrast(120%);
    }

    section figcaption {
        position: absolute;
        bottom: -30px; 
        left: 0;
        right: 0;
        margin: 0 auto; 
        font-size: 18px;
        color: #333; 
        background-color: rgba(255, 255, 255, 0.8); 
        padding: 5px 10px; 
        border-radius: 5px; 
    }
</style>

<div class="row">
    <div class="col-md-6 my-3">
        <h1 class="h3 mb-2 text-gray"><i class="fas fa-bell"></i> Solicitudes de Producción</h1>
    </div>
</div>

<!-- Imagenes de las galletas -->
<section>
    {% for receta in recetas %}
    <figure>
        <form method="POST" action="" class="solicitudForm">
            <input type="hidden" name="receta_id" value="{{ receta.id }}">
            <button type="button" data-id="{{ receta.id }}" class="btn-img openModalBtn" style="background: none; border: none; padding: 0; margin: 0; cursor: pointer;" data-toggle="modal" data-target="#modalConfirmacion">
                <img src="data:image/png;base64,{{ receta.imagen }}" alt="{{ receta.nombre }}">
            </button>
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        </form>
        <figcaption>{{ receta.nombre }}</figcaption>
    </figure>
    {% endfor %}
</section>

<!-- Tabla de todas las solicitudes -->
<div class="card shadow mb-4 mt-5" id="spacesTable">
    <div class="card-body">
        <div class="scrollable-table" style="overflow: auto; max-height: 400px;">
            <div class="row mt-4">
                <div class="col-md-12">
                    <h2 class="h5 mb-2 text-gray"><i class="fas fa-table"></i> Todas las Solicitudes</h2>
                    <input type="text" id="searchInput" class="form-control mb-3" placeholder="Buscar...">
                    <table class="table table-striped table-bordered table-hover" id="solicitudesTable">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Receta</th>
                                <th>Fecha de Solicitud</th>
                                <th>Lote</th>
                                <th>Estatus</th>
                                <th>Empleado</th>
                                <th>Empleado produccion</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for solicitud in solicitudes %}
                            <tr>
                                <td>{{ solicitud.id }}</td>
                                <td>{{ solicitud.receta.nombre }}</td>
                                <td>{{ solicitud.fecha_solicitud }}</td>
                                <td>{{ solicitud.lote }}</td>
                                <td>{{ solicitud.estatus }}</td>
                                <td>{{ solicitud.empleadoSolicitante }}</td>
                                <td>{{ solicitud.empleadoProduccion }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Modal de confirmación -->
<div class="modal fade" id="modalConfirmacion" tabindex="-1" aria-labelledby="modalConfirmacion" aria-hidden="true" role="dialog">
    <div class="container mt-5 modal-dialog" role="document">
        <div class="row modal-content" style="display: contents;">
             <div class="col-md-12 offset-md-3 mx-0">
               <div class="card">
                 <div class="card-body">
                   <h1 class="card-title text-center">Confirmar la solicitud</h1>
                   <p class="card-text text-center">Estás a punto de agregar la solicitud</p>
                   <div class="text-center">
                       <form action="{{ url_for('solicitudProduccion.agregar_solicitud')}}" method="post" class="d-inline">
                          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                          <input type="hidden" name="receta_id" id="recetaId">
                          <button type="submit" class="btn btn-success">Agregar</button>
                       </form>
                       <button type="button" id="closeModalConfirmacion" class="closeModalConfirmacion btn btn-danger">
                          Cancelar
                       </button>
                   </div>
                 </div>
               </div>
             </div>
        </div>
    </div>
  </div>

  <script src="{{ url_for('static', filename='jquery/jquery.min.js') }}"></script>

<script>

    document.addEventListener("DOMContentLoaded", function() {
        const searchInput = document.getElementById('searchInput');
        const userTable = document.getElementById('solicitudesTable');
        const rows = userTable.getElementsByTagName('tr');
    
        searchInput.addEventListener('input', function() {
          const searchText = this.value.toLowerCase();
          for (let i = 1; i < rows.length; i++) {
            const row = rows[i];
            const cells = row.getElementsByTagName('td');
            let found = false;
            for (let j = 0; j < cells.length; j++) {
              const cell = cells[j];
              if (cell.textContent.toLowerCase().indexOf(searchText) > -1) {
                found = true;
                break;
              }
            }
            if (found) {
              row.style.display = '';
            } else {
              row.style.display = 'none';
            }
          }
        });
      });

    $(document).ready(function () {
        $('.openModalBtn').click(function () {
            var recetaId = $(this).data('id');
            $('#recetaId').val(recetaId);
            $('#modalConfirmacion').modal('show');
        });

        $('#closeModalConfirmacion').click(function () {
            $('#modalConfirmacion').modal('hide');
        });
    });
</script>

{% endblock %}